### PR TITLE
Bump aws-sdk version for grails 2 branch

### PR DESCRIPTION
**Pull request by theaspect**

### CODE REVIEW

**Comment by benorama** [comment]
Sorry, but this branch is not maintained anymore.
Did you try to add `compile 'com.amazonaws:aws-java-sdk:1.11.126` to your app dependencies?
It should also work.

**Comment by theaspect** [comment]
@benorama yes, we still use Grails 2 and I wanted to have canonical version on maven repo like 1.11.126, even without changes in API

**Comment by theaspect** [comment]
@benorama could you tag the commit with `1.11.126` release and deploy to the grails repo

**Comment by benorama** [comment]
@theaspect It should be done now

**Pull request merged**
