### PR TITLE
DKIM fix for sendEmailWithAttachment.

### PR DESCRIPTION
**Pull request by chrisagiftbit**
Add the the From:, Reply-to, and To: headers to sendEmailWithAttachment. The lack of a From: header breaks DKIM.

### CODE REVIEW

**Comment by musketyr** [comment]
Hi, thanks for your contribution!

Your change is currently breaking existing tests here:

https://github.com/agorapulse/grails-aws-sdk/blob/master/groovy-aws-sdk-ses/src/test/groovy/com/agorapulse/awssdk/ses/AwsSesMailerSpec.groovy#L73-L91

**Comment by chrisagiftbit** [comment]
It is indeed failing. I looked into it, and I found that that test is failing because the system properties TEST_INBOX_EMAIL and TEST_FROM_EMAIL aren't set, so it's passing null to "to" and "from". When I set those properties locally, it passes. If you look at the details for the CI build, notice that it says "4 tests completed, 1 failed, 2 skipped". The 2 skipped confirms to me that some properties aren't set, as the two tests after the failing one are set to not run without them.

Previously, the test would pass despite those being null, but the changes in this PR make those values required.

I have some ideas. I can fix the PR so that the test will pass despite setting "to" and "from" to null, or I can add the @IgnoreIf annotation to the failing test so that it won't run without those values set, or you could set those properties on the CI server... What do you think is best?

**Comment by chrisagiftbit** [comment]
I updated my PR. I added a null check for a missing sourceEmail to AwsSesMailer. It didn't make any sense to me to add a null check to the recipients list, though, because that should throw an exception if you're trying to send an email to null. So I removed the to: parameter from the test instead. This way, it still runs and it still tests what it needs to.

**Comment by musketyr** [comment]
great, thanks!

**Pull request merged**
